
lane :lint do

    swiftLint(
        mode: :lint, 
        config_file: '.swiftlint.yml'
    )
end

platform :ios do

  desc "Runs all the tests"
  lane :test do
    
    carthage(
      platform: "iOS",
      use_binaries: false
    )
    
    scan(
      scheme: "FX-iOS",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
          
  end
  
end

platform :mac do
  
  desc "Runs all the tests"
  lane :test do
    
    carthage(
      platform: "Mac",
      use_binaries: false      
    )    

    scan(
      scheme: "FX-OSX",
      output_directory: ".ci/xcodebuild-data/",
      xcargs: "-derivedDataPath .ci/xcodebuild-data/"
    )
    
  end
  
end
